baseURL = 'https://savethehub.org/'
languageCode = 'en-us'
title = 'Arkansas Innovation Hub'
theme = 'docsy'

# Enable GitInfo for last modified dates
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Disable unused languages
disableLanguages = []

# Useful for RSS
[sitemap]
  changefreq = "monthly"
  priority = 0.5

# Image processing configuration
[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  anchor = "smart"

# Language configuration
[languages]
[languages.en]
  languageName = "English"
  weight = 1
  title = "Arkansas Innovation Hub"

# FIXED: Move description to params
[languages.en.params]
  description = "Community-owned makerspace, agriculture, and arts center in North Little Rock, Arkansas"

# Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "tango"

# Site params
[params]
  description = "The Arkansas Innovation Hub is a community-owned cooperative combining makerspace, agricultural innovation, and arts support to empower entrepreneurs, students, and creatives across Arkansas."
  copyright = "Arkansas Innovation Hub Cooperative"

  # Privacy settings
  privacy_policy = "https://savethehub.org/privacy/"

  # Repository information
  github_repo = "https://github.com/sshellabarger/savethehub"
  github_project_repo = "https://github.com/sshellabarger/savethehub"
  github_branch = "main"

  # Enable Git info for showing last updated dates
  github_subdir = ""
  time_format_blog = "Monday, January 02, 2006"
  time_format_default = "January 2, 2006"

  # RSS
  rss_sections = ["blog"]

  # UI Configuration
  [params.ui]
    sidebar_menu_compact = true
    sidebar_search_disable = false
    navbar_logo = true
    navbar_translucent_over_cover_disable = false
    footer_about_disable = false

    # Feedback
    [params.ui.feedback]
      enable = true
      yes = 'Glad to hear it! Please <a href="https://github.com/sshellabarger/savethehub/issues/new">tell us how we can improve</a>.'
      no = 'Sorry to hear that. Please <a href="https://github.com/sshellabarger/savethehub/issues/new">tell us how we can improve</a>.'

    # Readability
    [params.ui.readingtime]
      enable = true

  # Links shown in the footer
  [params.links]
    [[params.links.user]]
      name = "Email Us"
      url = "mailto:savethehub@protonmail.com"
      icon = "fa fa-envelope"
      desc = "Contact the Hub"
    [[params.links.user]]
      name = "Facebook"
      url = "https://www.facebook.com/ARInnovationHub"
      icon = "fab fa-facebook"
      desc = "Follow us on Facebook"
    [[params.links.user]]
      name = "Instagram"
      url = "https://www.instagram.com/armakehub"
      icon = "fab fa-instagram"
      desc = "Follow us on Instagram"
    [[params.links.developer]]
      name = "GitHub"
      url = "https://github.com/sshellabarger/savethehub"
      icon = "fab fa-github"
      desc = "Project repository"
    [[params.links.developer]]
      name = "Get Involved"
      url = "/get-involved/contact/"
      icon = "fa fa-users"
      desc = "Join the cooperative"

# Main menu
[menu]
  [[menu.main]]
    name = "About"
    weight = 10
    url = "/about/"
  [[menu.main]]
    name = "Financials"
    weight = 20
    url = "/financials/"
  [[menu.main]]
    name = "Programming"
    weight = 30
    url = "/programming/"
  [[menu.main]]
    name = "Operations"
    weight = 40
    url = "/operations/"
  [[menu.main]]
    name = "Get Involved"
    weight = 50
    url = "/get-involved/"
  [[menu.main]]
    name = "News"
    weight = 60
    url = "/blog/"

# Module configuration
[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
